name: marlin_auto_build

on:
  workflow_dispatch:  # Позволяет вручную запускать workflow
  schedule:
    - cron: '30 3 * * *'  # Запуск по расписанию каждый день в 03:30 UTC

jobs:
  create_builds:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Build Marlin Firmware
        uses: zisismaras/marlin_auto_build@master

      - name: Upload Firmware Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: marlin-firmware  # Имя для артефакта
          path: path/to/your/output/*.bin  # Путь к вашим сгенерированным .bin файлам
